### ISSUE TITLE
Suggestion on handling of stimuli-related parameters and metadata

### ISSUE THREAD

**Issue by JernejaR** [DanielDondorp/BehaviourAnalysis#2]
I suggest reorganizing stimuli-related columns for easy grouping and comparisons across different stimuli groups:
-Current ‘stimuli’ column should be renamed to ‘number_of_stimuli’
-New column called ‘stimuli’ or ‘stimuli class’ or similar should be made, that reads ‘none’ for the data without stimulation, and for data with light stimuli the class should be extracted and labeled as ‘green’, ‘red’, ‘blue’, ‘white’ for simple single-stimuli-single-color experiments. Label ‘mix’/’complex’ or similar for complex and/or wrong stimuli (i.e. more than 1 stimuli and/or color) for now. In the future you can also create new vibration classes, combined classes etc.
-If future experiments have stimuli of differing temporal composition, this can be added as a ‘stimuli_sequence’ column to sort your 1min stimuli from your 5-times-5seconds stimuli of same colour/vibration intensity etc.
-The deltas can then be reduced to just ‘delta_(ON/OFF)_(name of column)’ and compared between different stimuli settings (+ in the case of several stimuli in same experiment maybe add counter to deltas?)

**Comment by DanielDondorp** [comment]
Yes. Good suggestions. I'll get on this when time allows. I`ll just have to think about how old dataframes are seen when we change the meaning of a column name, but I guess data will have to be passed through the analysis again when we update this anyways.
