### ISSUE TITLE
New parameters request

### ISSUE THREAD

**Issue by JernejaR** [DanielDondorp/BehaviourAnalysis#4]
For parameters with values centred around 0 (e.g. accelerations) a variance metaparameter would be very useful (either variance or standard deviation), since that is more likely to vary between groups than range and mean values. 
We also need additional parameters for turn values. Calculate mean_ and var_turns as now, but only counting in values at swimming speeds (>500).

**Comment by DanielDondorp** [comment]
Request granted. 

I have added the parameters. Could you please test it on your data as well and get back to me?

**Comment by DanielDondorp** [comment]
It should be functional now.
